spring:
  datasource:
    url: jdbc:h2:mem:eazybank;DATABASE_TO_LOWER=true;DB_CLOSE_DELAY=-1;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false # https://www.baeldung.com/spring-open-session-in-view
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      platform: h2
      schema-locations:
      data-locations: classpath:sql/h2-data.sql
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG